### ISSUE TITLE
Unable to get working with 0.9.7

### ISSUE THREAD

**Issue by levibutler** [grncdr/guacamole-auth-hmac#12]
Hello, After a bit more playing about i managed to get 1.0.1 to compile.
Sadly im still unable to get any further than the login screen though.

Im getting a 403 from guacamole/api/tokens
{"message":"Permission Denied.","expected":[{"name":"username","type":"USERNAME"},{"name":"password","type":"PASSWORD"}],"type":"INVALID_CREDENTIALS"}

I have checked my syslog and catalina.out for errors but cant see any.

I have modified the guacamole.properties
guacd-hostname: localhost
guacd-port: 4822
lib-directory: /var/lib/tomcat7/webapps/guacamole/WEB-INF/classes
auth-provider: com.stephensugden.guacamole.net.hmac.HmacAuthenticationProvider
secret-key: secret
timestamp-age-limit: 0

im running guacamole version 0.9.7
when i use the user-mapping.xml i am able to login and connect to servers successfully
Thanks in advance

**Comment by melhemmaroun** [comment]
Hi, I saw your message earlier sorry for replying late. With 0.9.3 I got it to work some time ago even before posting here with easy hmac, It didn't work with 0.9.7 with me. If u have any news please let me know.
Thanks,
Melhem.

**Comment by levibutler** [comment]
Thanks, ill try installing 0.9.3

**Comment by levibutler** [comment]
all working with 0.9.3
Thanks

**Comment by goofy79** [comment]
Hello,

i have exact the same problem, but i try with the 0.9.8.

**Comment by levibutler** [comment]
Hi - Let me know if you get it going - i would really like to upgrade mine :)
Thanks

**Comment by markushutter** [comment]
Hi @all,

is their any newer version who works? I try ist with 0.9.9 and i always getting a 403 from guacamole/api/tokens
{"message":"Permission Denied.","expected":[{"name":"username","type":"USERNAME"},{"name":"password","type":"PASSWORD"}],"type":"INVALID_CREDENTIALS"}

I look forward to any help from you.

Thanks a lot

**Comment by canzone** [comment]
Hello,

I just finished installing 0.9.10 with Java 8 and Tomcat8 and I'm facing the exact same issue. Nothing in the logs, and a 403 from guacamole/api/tokens. Any ideas?

Thanks!

**Comment by bpeters-cmu** [comment]
I am facing the same issue with 0.9.12

**Comment by divyeshg94** [comment]
Still facing this issue in version 1.0.0

**Comment by Kyvix** [comment]
Still facing this issue in version 1.2.0

{
    "message": "Invalid login",
    "translatableMessage": {
        "key": "APP.TEXT_UNTRANSLATED",
        "variables": {
            "MESSAGE": "Invalid login"
        }
    },
    "statusCode": null,
    "expected": [
        {
            "name": "username",
            "type": "USERNAME"
        },
        {
            "name": "password",
            "type": "PASSWORD"
        }
    ],
    "type": "INVALID_CREDENTIALS"
}

Was anyone able to solve this problem ?

**Comment by remchuk** [comment]
Any news on this?
